// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {

      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3Oq3mO4K8gfUWHE6LKejKbavifeVSLA',
    appId: '1:554708472825:web:2ed710c8866e848c176328',
    messagingSenderId: '554708472825',
    projectId: 'chumma-243ca',
    authDomain: 'chumma-243ca.firebaseapp.com',
    storageBucket: 'chumma-243ca.appspot.com',
    measurementId: 'G-LN98GGKKE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFj-UouTK2XU7UWCLZXfoBLs8w5XBjG8',
    appId: '1:554708472825:android:dfe635e805d880e1176328',
    messagingSenderId: '554708472825',
    projectId: 'chumma-243ca',
    storageBucket: 'chumma-243ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfZgN_KjgGFxe8QFAT8ER1ZP8HYS6TVM',
    appId: '1:554708472825:ios:11afbac3500344d1176328',
    messagingSenderId: '554708472825',
    projectId: 'chumma-243ca',
    storageBucket: 'chumma-243ca.appspot.com',
    iosClientId: '554708472825-oql28i34galrnpekae8pl017u2pnj8t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chumma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfZgN_KjgGFxe8QFAT8ER1ZP8HYS6TVM',
    appId: '1:554708472825:ios:11afbac3500344d1176328',
    messagingSenderId: '554708472825',
    projectId: 'chumma-243ca',
    storageBucket: 'chumma-243ca.appspot.com',
    iosClientId: '554708472825-oql28i34galrnpekae8pl017u2pnj8t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chumma',
  );
}
